### ISSUE TITLE
Order Attributions (aka UTM trackers)

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/checkout-ui-extensions#14]
## Problem

We want to send order attributions from utm trackers to the iFixit api when a user completes a checkout.

## Do this

- [Create](https://shopify.dev/docs/apps/marketing/pixels/getting-started) a web pixel extension
- [Read](https://shopify.dev/docs/api/pixels/pixel-extension#browser-cookie-get-name) a UTM cookie from www.ifixit.com (we'll be on store.ifixit.com, so this should be ok)
  - Make an issue/PR on iFixit/ifixit to store utm info in a cookie, alongside sending it as a query param to checkout (what we currently do).
- [Subscribe](https://shopify.dev/docs/apps/marketing/pixels/getting-started#step-4-subscribe-to-events-in-web-pixel) to the [`checkout_completed`](https://shopify.dev/docs/api/pixels/customer-events#checkout_completed) event. When this event is emitted, [send](https://shopify.dev/docs/api/pixels/pixel-extension#browser-sendbeacon-url-data) the utm trackers to the ifixit order attributions api (see how we do it in [shopify-v2](https://github.com/iFixit/shopify-v2/blob/master/src/scripts/checkout/checkout-order-attributions.js)).
- Clear the utm cookie (?)

Similar to:
- https://github.com/iFixit/ifixit/issues/40622
- https://github.com/iFixit/shopify-v2/issues/732

**Comment by danielcliu-ifixit** [comment]
Hey thinking this over a bit, is there any need to put the utm in a cookie? Do we not expect url parameters to persist?

**Comment by masonmcelvain** [comment]
I don't know of a way to read the url from the pixel. I suggested that we use a cookie because we can read cookies from the pixel ([docs](https://shopify.dev/docs/api/web-pixels-api/standard-api/browser#properties-propertydetail-cookie)).

**Comment by danielcliu-ifixit** [comment]
Ok cool it seems there is a way to[ access the url](https://shopify.dev/docs/api/web-pixels-api/standard-api/init#properties-propertydetail-context) from the pixel
