### ISSUE TITLE
Synchronize login state with iFixit

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/checkout-ui-extensions#37]
shopify-v2 [implementation](https://github.com/iFixit/shopify-v2/blob/d6ccef2ea90525af35749fb33bea8c7e823b424b/src/scripts/components/login-state-sync.js#L27)

**Comment by danielcliu-ifixit** [comment]
im actually a little worried about this feature in general. Im not sure our system currently handles login/logging out well in checkout, as wouldn't now technically tie a cart to an incorrect user/guest? Im unsure of how we want to handle this, considering that we ideally would want to keep our ifixit carts in sync with shopify

**Comment by masonmcelvain** [comment]
Danny, Daniel and I discussed this and had the idea of logging anonymous users out on Shopify before sending them to checkout. We already log users in on Shopify with multipass before sending them to checkout with the `return_to` param. This approach seems easier/more feasible than anything else we could thing of during checkout, pending experimentation to see if it works.

**Comment by masonmcelvain** [comment]
After experimenting it seems like the `/account/logout` resource only works on the checkout page in shopify-v2. If called from a different domain (like www.cominor.com or the checkout extensibility web worker), the request is blocked by CORS. `await fetch('${storeOrigin}/account/logout', { mode: 'no-cors' });` gets a 302 response like in shopify-v2 but does not seem to have an effect. The customer is still logged in when they first reach checkout.

**Comment by masonmcelvain** [comment]
Danny figured it out! `/account/logout?return_url=checkoutUrl`
